### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 - torch.unsqueeze() / torch.squeeze()

In [4]:
# Example 1 - Unsqueeze the tensor
t = torch.ones((6,3))
u = torch.unsqueeze(t,dim=2)
print(t.shape)
print(t)
print(u.shape)
print(u)


torch.Size([6, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([6, 3, 1])
tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])


In [5]:
# Example 2 - Squeeze the tensor
t = torch.ones((2,1,3,1))
v = torch.squeeze(t)
print(t.shape)
print(t)
print(v.shape)
print(v)

torch.Size([2, 1, 3, 1])
tensor([[[[1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.]]]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Function 2 - Fill diagonal

In [6]:
# Example 1 - Fill diagonal of a tensor
t = torch.zeros((6,3))
print(t)
print(t.fill_diagonal_(5))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# Example 2 - Fill diagonal of a tensor with wrapping
print(t.fill_diagonal_(5,wrap=True))

tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.],
        [0., 0., 0.],
        [5., 0., 0.],
        [0., 5., 0.]])


### Function 3 - torch.reshape() / tensor.view()

In [8]:
# Example 1 - Change the shape of tensor
t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                  [[2,3,4,5],[6,7,8,9],[8,9,10,11]]])
print(f'Shape of t : {t.shape}')
t1 = t.reshape(6,4)
t2 = t.view(6,4)
print(t1.shape,t2.shape)
print(t1,'\n',t2)

Shape of t : torch.Size([2, 3, 4])
torch.Size([6, 4]) torch.Size([6, 4])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [ 8,  9, 10, 11]]) 
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [ 8,  9, 10, 11]])


In [9]:
# Example 2 - Change the shape of tensor then addition
a = torch.ones_like(t)
print(f'Shape of a : {a.shape}')
a1 = a.reshape(6,4)
print(f'Shape of a1 : {a1.shape}')
a1 + t1

Shape of a : torch.Size([2, 3, 4])
Shape of a1 : torch.Size([6, 4])


tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13],
        [ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [ 9, 10, 11, 12]])

### Function 4 - tensor.transpose() / tensor.permute()

In [10]:
# Example 1 - Exchange the dimension of a tensor
t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                  [[2,3,4,5],[6,7,8,9],[8,9,10,11]]])
print(t.shape)
print(t)

t1 = t.transpose(0,1)
t2 = t.permute((1,0,2))
print(t1.shape,t2.shape)
print(t1,'\n',t2)

torch.Size([2, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [ 8,  9, 10, 11]]])
torch.Size([3, 2, 4]) torch.Size([3, 2, 4])
tensor([[[ 1,  2,  3,  4],
         [ 2,  3,  4,  5]],

        [[ 5,  6,  7,  8],
         [ 6,  7,  8,  9]],

        [[ 9, 10, 11, 12],
         [ 8,  9, 10, 11]]]) 
 tensor([[[ 1,  2,  3,  4],
         [ 2,  3,  4,  5]],

        [[ 5,  6,  7,  8],
         [ 6,  7,  8,  9]],

        [[ 9, 10, 11, 12],
         [ 8,  9, 10, 11]]])


In [11]:
# Example 2 - matrix multiplication
a = torch.tensor([1,1,1])
print('Shape a:',a.shape)
print('Shape t:',t.shape)
print('transpose t and do matrix multiplication with a:')
t3 = t.transpose(1,2)
print(t3)
print('Shape t3:',t3.shape)
print('Shape t3@a :',(t3@a).shape)
t3@a

Shape a: torch.Size([3])
Shape t: torch.Size([2, 3, 4])
transpose t and do matrix multiplication with a:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[ 2,  6,  8],
         [ 3,  7,  9],
         [ 4,  8, 10],
         [ 5,  9, 11]]])
Shape t3: torch.Size([2, 4, 3])
Shape t3@a : torch.Size([2, 4])


tensor([[15, 18, 21, 24],
        [16, 19, 22, 25]])